/**********************************************************************************************************************
 * \file Delay.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Delay.h"

#include "Bsp.h"
#include "Platform_Types.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
sint32 Ms_To_Stm_Ticks(uint32 millis) {
    return IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, millis);
}

sint32 Us_To_Stm_Ticks(uint32 micros) {
    return IfxStm_getTicksFromMicroseconds(BSP_DEFAULT_TIMER, micros);
}

void Delay_Sec(uint32 second) {
    Ifx_TickTime ticks = Ms_To_Stm_Ticks(second * 1000);
    waitTime(ticks);
}

void Delay_Ms(uint32 millis) {
    Ifx_TickTime ticks = Ms_To_Stm_Ticks(millis);
    waitTime(ticks);
}

void Delay_Us(uint32 micros) {
    Ifx_TickTime ticks = Us_To_Stm_Ticks(micros);
    waitTime(ticks);
}

uint64 Get_Cur_Seconds(void) {
    return IfxStm_get(&MODULE_STM0) / IfxStm_getFrequency(&MODULE_STM0);
}

uint64 Get_Cur_Millis(void) {
    return IfxStm_get(&MODULE_STM0) / IfxStm_getFrequency(&MODULE_STM0) * 1000;
}

uint64 Get_Cur_Micros(void) {
    return IfxStm_get(&MODULE_STM0) / IfxStm_getFrequency(&MODULE_STM0) * 1000000;
}
