/**********************************************************************************************************************
 * \file Pwm.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Pwm.h"

#include "Platform_Types.h"
#include "IfxGtm_Tom_Pwm.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void Init_Pwm(Pwm *pwm, IfxGtm_Tom_ToutMap *tom, uint16 period, uint16 duty_cycle)
{
    /* Initialize the configuration structure with default parameters */
    IfxGtm_Tom_Pwm_initConfig(&pwm->config, &MODULE_GTM);

    pwm->config.tom = tom->tom;                                      /* Select the TOM depending on the LED          */
    pwm->config.tomChannel = tom->channel;                           /* Select the channel depending on the LED      */
    pwm->config.period = period;                                    /* Set the pwm period                           */
    pwm->config.dutyCycle = duty_cycle;                              /* Set the pwm duty cycle                       */
    pwm->config.pin.outputPin = tom;                               /* Set the LED port pin as output               */
    pwm->config.synchronousUpdateEnabled = TRUE;                                    /* Enable synchronous update                    */

    IfxGtm_Tom_Pwm_init(&pwm->driver, &pwm->config);                /* Initialize the GTM TOM                       */

    IfxGtm_Tom_Pwm_start(&pwm->driver, TRUE);                       /* Start the PWM                                */
}

void Set_Duty_Cycle(Pwm *pwm, uint32 duty_cycle)
{
    pwm->config.dutyCycle = duty_cycle;
    IfxGtm_Tom_Pwm_init(&pwm->driver, &pwm->config);                /* Initialize the GTM TOM                       */
}

void Set_Duty_Period(Pwm *pwm, uint32 period)
{
    pwm->config.period = period;                              /* Change the period           */
    IfxGtm_Tom_Pwm_init(&pwm->driver, &pwm->config);                /* Re-initialize the PWM                        */
}

void Set_Duty_Ratio(Pwm *pwm, uint8 duty_ratio)
{
    uint32 duty_cycle = (uint32)(0.01f * duty_ratio * pwm->config.period);
    Set_Duty_Cycle(pwm, duty_cycle);
}

void Set_Pwm_Period(Pwm *pwm, uint32 period) {
    // 듀티비는 유지하되, ticks 수만을 늘리는것.
    float32 ratio = (float32)pwm->config.dutyCycle / pwm->config.period;
    pwm->config.period = period;
    pwm->config.dutyCycle = (uint32)(period * ratio);
    IfxGtm_Tom_Pwm_init(&pwm->driver, &pwm->config);
}
