/**********************************************************************************************************************
 * \file Ultrasonic.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ultrasonic.h"

#include "Platform_Types.h"
#include "IfxPort.h"
#include "IfxCpu.h"
#include "IfxStm.h"

#include "Delay.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define TIMEOUT     23529

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
uint32 Pulse_In(IfxPort_Pin pin, uint8 state, uint32 timeout);

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void Init_Ultrasonic(Ultrasonic *config) {
    IfxPort_setPinModeOutput(config->trig.port, config->trig.pinIndex, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinModeInput(config->echo.port, config->echo.pinIndex, IfxPort_InputMode_pullUp);
}

float32 Get_Ultrasonic_Distance(Ultrasonic *config) {
    IfxPort_setPinLow(config->trig.port, config->trig.pinIndex);
    Delay_Us(2);
    IfxPort_setPinHigh(config->trig.port, config->trig.pinIndex);
    Delay_Us(10);
    IfxPort_setPinLow(config->trig.port, config->trig.pinIndex);

    boolean interrupt_state = IfxCpu_disableInterrupts();

    uint32 micros = Pulse_In(config->echo, TRUE, TIMEOUT);

    IfxCpu_restoreInterrupts(interrupt_state);

    return (float32)micros / 58.8235f;
}

uint32 Pulse_In(IfxPort_Pin pin, boolean state, uint32 timeout) {
    uint32 start_micros = Get_Cur_Micros();

    // wait for any previous pulse to end
    while (__getbit(&pin.port->IN.U, pin.pinIndex) == state) {
        if (Get_Cur_Micros() - start_micros >= timeout) {
            return 0;
        }
    }

    // wait for the pulse to start
    while (__getbit(&pin.port->IN.U, pin.pinIndex) != state) {
        if (Get_Cur_Micros() - start_micros >= timeout) {
            return 0;
        }
    }

    // wait for the pulse to stop
    uint32 estimation_start = Get_Cur_Micros();
    while (__getbit(&pin.port->IN.U, pin.pinIndex) == state) {
        if (Get_Cur_Micros() - start_micros >= timeout) {
            return 0;
        }
    }
    uint32 estimation_end = Get_Cur_Micros();

    return estimation_end - estimation_start;
}
