/**********************************************************************************************************************
 * \file ECU_Command.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "IfxPort.h"
#include "IfxStm.h"

#include "ECU_Module.h"
#include "App_Module.h"
#include "Audio_Module.h"
#include "Door_Module.h"
#include "In_Module_Switch_Door_Close.h"
#include "In_Module_Switch_Door_KidLock.h"
#include "In_Module_Switch_Door_OnOff.h"
#include "In_Module_Switch_Door_Open.h"
#include "XIO.h"
#include "Out_Module.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define LOCK 0
#define UNLOCK 1

#define IDLE 10
#define OPEN 11
#define CLOSE 12
#define DANGER 13
#define KIDSLOCK 14

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
int Security_State = LOCK;
int Motion_State = IDLE;

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/
int receive_raspberry = 0; // 초기값은 0 -> LOCK이라는 의미로

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void ECU_Module_Init(){
    // 구현하기.
    App_Module_init();
    Audio_Module_init();
    Door_Module_init();
    //void In_Module_Switch_Door_Close_init(TC275 (PINnum))
    //void In_Module_Switch_Door_KdL_init(TC275 (PINnum))
    //void In_Module_Switch_Door_OnOff_init(TC275 (PINnum))
    //void In_Module_Switch_Door_Open_init(TC275 (PINnum))
    Out_Module_init();

    return;
}

void reveive_raspberry_digtalpin_input_set(){
    // input setting (인피니언 Digital 49번 핀 사용). <Digital pin 49 / XIO.30 / P21.0 >

    return;
}

void Race_Start(){

    // App에서 송신한 데이터를 받는다.
    // 현재는 그냥 true로 (1)로 해둔 것. 이후에 수정해야함.
    /*switch(Security_State){
        case LOCK:

    }*/

    Play_DoorOpen_Sound();

    return;
}
