/**********************************************************************************************************************
 * \file myPwm.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "myPwm.h"
#include "IfxPort.h"
#include "IfxGtm_Tom_Pwm.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define PWM_PERIOD 50000
#define FADE_STEP           PWM_PERIOD / 100
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IfxGtm_Tom_Pwm_Config g_tomConfig;
IfxGtm_Tom_Pwm_Driver g_tomDriver;

uint32 g_fadeValue = 0;
sint8 g_fadeDir = 1;
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void setTomConfig(uint8 port, uint8 pin);

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void setPinModePWM(uint8 port, uint8 pin)
{
    IfxGtm_enable(&MODULE_GTM);                                     /* Enable GTM                                   */

    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_FXCLK);   /* Enable the FXU clock                         */

    /* Initialize the configuration structure with default parameters */
    // default period 20, cycle 10, ratio 50%
    IfxGtm_Tom_Pwm_initConfig(&g_tomConfig, &MODULE_GTM);

    setTomConfig(port, pin);

    IfxGtm_Tom_Pwm_init(&g_tomDriver, &g_tomConfig);
    IfxGtm_Tom_Pwm_start(&g_tomDriver, TRUE);
}

void setTomConfig(uint8 port, uint8 pin)
{
    g_tomConfig.period = PWM_PERIOD;
    g_tomConfig.synchronousUpdateEnabled = TRUE;

    if (port == 15 && pin == 3)
    {
        g_tomConfig.tom = PWML_1.tom;
        g_tomConfig.tomChannel = PWML_1.channel;
        g_tomConfig.pin.outputPin = &PWML_1;         /* Set the port pin as output               */
    }
    else if (port == 15 && pin == 2)
    {
        g_tomConfig.tom = PWML_2.tom;
        g_tomConfig.tomChannel = PWML_2.channel;
        g_tomConfig.pin.outputPin = &PWML_2;   /* Set the port pin as output               */
    }
    else if (port == 2 && pin == 0)
    {
        g_tomConfig.tom = PWML_3.tom;
        g_tomConfig.tomChannel = PWML_3.channel;
        g_tomConfig.pin.outputPin = &PWML_3;   /* Set the port pin as output               */
    }
    else if (port == 2 && pin == 1)
    {
        g_tomConfig.tom = PWML_4.tom;
        g_tomConfig.tomChannel = PWML_4.channel;
        g_tomConfig.pin.outputPin = &PWML_4;
    }
    else if (port == 10 && pin == 4)
    {
        g_tomConfig.tom = PWML_5.tom;
        g_tomConfig.tomChannel = PWML_5.channel;
        g_tomConfig.pin.outputPin = &PWML_5;
    }
    else if (port == 2 && pin == 3)
    {
        g_tomConfig.tom = PWML_6.tom;
        g_tomConfig.tomChannel = PWML_6.channel;
        g_tomConfig.pin.outputPin = &PWML_6;
    }
    else if (port == 2 && pin == 4)
    {
        g_tomConfig.tom = PWML_7.tom;
        g_tomConfig.tomChannel = PWML_7.channel;
        g_tomConfig.pin.outputPin = &PWML_7;
    }
    else if (port == 2 && pin == 5)
    {
        g_tomConfig.tom = PWML_8.tom;
        g_tomConfig.tomChannel = PWML_8.channel;
        g_tomConfig.pin.outputPin = &PWML_8;
    }
    else if (port == 2 && pin == 6)
    {
        g_tomConfig.tom = PWMH_1.tom;
        g_tomConfig.tomChannel = PWMH_1.channel;
        g_tomConfig.pin.outputPin = &PWMH_1;
    }
    else if (port == 2 && pin == 7)
    {
        g_tomConfig.tom = PWMH_2.tom;
        g_tomConfig.tomChannel = PWMH_2.channel;
        g_tomConfig.pin.outputPin = &PWMH_2;
    }
    else if (port == 10 && pin == 5)
    {
        g_tomConfig.tom = PWMH_3.tom;
        g_tomConfig.tomChannel = PWMH_3.channel;
        g_tomConfig.pin.outputPin = &PWMH_3;
    }
    else if (port == 10 && pin == 3)
    {
        g_tomConfig.tom = PWMH_4.tom;
        g_tomConfig.tomChannel = PWMH_4.channel;
        g_tomConfig.pin.outputPin = &PWMH_4;
    }
    else if (port == 10 && pin == 1)
    {
        g_tomConfig.tom = PWMH_5.tom;
        g_tomConfig.tomChannel = PWMH_5.channel;
        g_tomConfig.pin.outputPin = &PWMH_5;
    }
    else if (port == 10 && pin == 2)
    {
        g_tomConfig.tom = PWMH_6.tom;
        g_tomConfig.tomChannel = PWMH_6.channel;
        g_tomConfig.pin.outputPin = &PWMH_5;
    }
    else if (port == 13 && pin == 2)
    {
        g_tomConfig.tom = PWMH_7.tom;
        g_tomConfig.tomChannel = PWMH_7.channel;
        g_tomConfig.pin.outputPin = &PWMH_7;
    }
    else if (port == 13 && pin == 1)
    {
        g_tomConfig.tom = PWMH_8.tom;
        g_tomConfig.tomChannel = PWMH_8.channel;
        g_tomConfig.pin.outputPin = &PWMH_8;
    }
}

/* This function sets the duty cycle of the PWM */
void setDutyCycle(uint32 dutyCycle)
{
    g_tomConfig.dutyCycle = dutyCycle;                              /* Change the value of the duty cycle           */
    IfxGtm_Tom_Pwm_init(&g_tomDriver, &g_tomConfig);                /* Re-initialize the PWM                        */
}

void setDutyPeriod(uint32 period)
{
    g_tomConfig.period = period;                              /* Change the value of the duty cycle           */
    IfxGtm_Tom_Pwm_init(&g_tomDriver, &g_tomConfig);                /* Re-initialize the PWM                        */
}

void setDutyRatio(uint8 ratio)
{
    // 듀티비 설정하기.
    g_tomConfig.dutyCycle = g_tomConfig.period * ratio / 100;
    IfxGtm_Tom_Pwm_init(&g_tomDriver, &g_tomConfig);
}

void setPwmPriod(uint32 period)
{
    // 듀티비는 유지하되, ticks 수만을 늘리는것.
    g_tomConfig.period = period;
    g_tomConfig.dutyCycle = period * g_tomConfig.dutyCycle / g_tomConfig.period;
    IfxGtm_Tom_Pwm_init(&g_tomDriver, &g_tomConfig);
}
