/**********************************************************************************************************************
 * \file myPwm.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef MYPWM_H_
#define MYPWM_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "IfxPort.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define PWML_1  IfxGtm_TOM1_6_TOUT74_P15_3_OUT
#define PWML_2  IfxGtm_TOM2_13_TOUT73_P15_2_OUT
#define PWML_3  IfxGtm_TOM0_8_TOUT0_P02_0_OUT
#define PWML_4  IfxGtm_TOM0_9_TOUT1_P02_1_OUT
#define PWML_5  IfxGtm_TOM0_6_TOUT106_P10_4_OUT
#define PWML_6  IfxGtm_TOM0_11_TOUT3_P02_3_OUT
#define PWML_7  IfxGtm_TOM0_12_TOUT4_P02_4_OUT
#define PWML_8  IfxGtm_TOM0_13_TOUT5_P02_5_OUT

#define PWMH_1  IfxGtm_TOM0_14_TOUT6_P02_6_OUT
#define PWMH_2  IfxGtm_TOM0_15_TOUT7_P02_7_OUT
#define PWMH_3  IfxGtm_TOM0_2_TOUT107_P10_5_OUT
#define PWMH_4  IfxGtm_TOM0_3_TOUT105_P10_3_OUT
#define PWMH_5  IfxGtm_TOM0_1_TOUT103_P10_1_OUT
#define PWMH_6  IfxGtm_TOM0_2_TOUT104_P10_2_OUT
#define PWMH_7  IfxGtm_TOM0_7_TOUT93_P13_2_OUT
#define PWMH_8  IfxGtm_TOM0_6_TOUT92_P13_1_OUT
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
 
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void setPinModePwm(uint8 port, uint8 pin);
void setPwmPriod(uint32 period);
void setDutyCycle(uint32 dutyCycle);
void setDutyRatio(uint8 ratio);
void fadeLED(void);

#endif /* MYPWM_H_ */
