/**********************************************************************************************************************
 * \file In_Module_Switch_Door.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define XIO22   {&MODULE_P14, 0}
#define XIO23   {&MODULE_P14, 1}
#define XIO24   {&MODULE_P15, 6}
#define XIO25   {&MODULE_P00, 0}
#define XIO26   {&MODULE_P00, 8}
#define XIO27   {&MODULE_P00, 1}
#define XIO28   {&MODULE_P00, 9}
#define XIO29   {&MODULE_P00, 2}
#define XIO30   {&MODULE_P00, 10}
#define XIO31   {&MODULE_P00, 3}
#define XIO32   {&MODULE_P00, 11}
#define XIO33   {&MODULE_P00, 4}
#define XIO34   {&MODULE_P00, 12}
#define XIO35   {&MODULE_P00, 5}
#define XIO36   {&MODULE_P33, 2}
#define XIO37   {&MODULE_P00, 6}
#define XIO38   {&MODULE_P33, 1}

#define XIO39   {&MODULE_P00, 7}
#define XIO40   {&MODULE_P33, 0}
#define XIO41   {&MODULE_P11, 9}
#define XIO42   {&MODULE_P11, 10}
#define XIO43   {&MODULE_P11, 11}
#define XIO44   {&MODULE_P33, 3}
#define XIO45   {&MODULE_P11, 2}
#define XIO46   {&MODULE_P11, 3}
#define XIO47   {&MODULE_P11, 6}
#define XIO48   {&MODULE_P00, 10}

#define XIO49   {&MODULE_P21, 0}
#define XIO50   {&MODULE_P33, 4}
#define XIO51   {&MODULE_P33, 12}
#define MAX_XIO_NUMBER  30  /*  XIO (PIN22) ~ (PIN50)      */
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
