/**********************************************************************************************************************
 * \file Audio_Module.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "IfxPort.h"
#include "IfxStm.h"
#include "Bsp.h"

#include "Audio_Module.h"
#include "myPwm.h"
#include "myGtm.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define WAIT_TIME 10
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
fxGtm_Tom_Pwm_Config tomConfig;
IfxGtm_Tom_Pwm_Config g_tomDriver;

soundDo(hz) {
    setdutycycle(&config)

/*
void Audio_Module_init(){

    // PWM 사용을 위한 세팅
//    setPinModePWM(2, 7); // PWMH 9번 사용.
    initGtm();

    // 부저 2개 사용 -> 2개 Setting
    initGtmTomPwm(PWMH2); // 부저1 PWM pin 9 연결
    initGtmTomPwm(PWMH3); // 부저2 PWM pin 10 연결

    return;
}

void Make_sound(unsigned int idx){
    float buzzer[2] = {261.686f, 500.262f};
    unsigned int uPeriod = (unsigned int)(100000000/buzzer[idx]);

    setDutyPeriod(PWMH2, uPeriod);
    setDutyRatio(PWMH2, 30);
}

void Play_DoorOpen_Sound(){
    /* Initialize a time variable */
    Ifx_TickTime ticksFor10ms = IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, WAIT_TIME);

    Make_sound(0);
    waitTime(ticksFor10ms * 100);
    Make_sound(1);
    waitTime(ticksFor10ms * 100);
}

// ------------------------- 부저 2개 각기 다른 period 인가가 되는지 확인하는 코드 ---------------------------------
void Make_sound_two_buzzer(unsigned int idx1, unsigned int idx2){
    float buzzer[2] = {261.686f, 100.262f};
    unsigned int uPeriod1 = (unsigned int)(100000000/buzzer[idx1]);
    unsigned int uPeriod2 = (unsigned int)(100000000/buzzer[idx2]);

    setDutyPeriod(PWMH2, uPeriod1);
    setDutyPeriod(PWMH3, uPeriod2);

    setDutyRatio(PWMH2, 50);
    setDutyRatio(PWMH3, 50);
}

void Play_DoorOpen_Sound_two_buzzer(){
    /* Initialize a time variable */
    Ifx_TickTime ticksFor10ms = IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, WAIT_TIME);

    Make_sound_two_buzzer(0, 1);
    waitTime(ticksFor10ms * 100);
    Make_sound_two_buzzer(1, 0);
    waitTime(ticksFor10ms * 100);
}
// ------------------------- 부저 2개 각기 다른 period 인가가 되는지 확인하는 코드 ---------------------------------

// ------------------------- LED 2개로 주기는 동일하게하고 듀티비를 다르게해서 테스트한 코드 ----------------------------
void test_led_init(){
    initGtm();
    initGtmTomPwm(PWML7); // PWM PIN 6
    initGtmTomPwm(PWML8); // PWM PIN 7
}

void test_led(){

    Ifx_TickTime ticksFor10ms = IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, WAIT_TIME);

    unsigned int uPeriod1 = (unsigned int)(100000000/200);
    unsigned int uPeriod2 = (unsigned int)(100000000/200);
    setDutyPeriod(PWML7, uPeriod1);
    setDutyPeriod(PWML8, uPeriod2);
    for(int i=1; i<100;i++){
        setDutyRatio(PWML7, i);
        setDutyRatio(PWML8, 100-i);

        waitTime(ticksFor10ms * 10);
    }
    return;
}
*/
// ------------------------- LED 2개로 주기는 동일하게하고 듀티비를 다르게해서 테스트한 코드 ----------------------------
