/**********************************************************************************************************************
 * \file Audio.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

    // TODO: Delay.h 라이브러리 이용해주기
    // TODO: f_buzz 배열 전역으로 관리해주기
    // TODO: uint32, float32 등의 타입 재저으이 사용해주기
    // TODO: Delay.h 추가하고나면 Bsp.h include list에서 삭제해주기
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Audio.h"

#include "Pwm.h"

#include "Platform_Types.h"
#include "IfxGtm_PinMap.h"
#include "Bsp.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define TOM_AUDIO   {IfxGtm_Tom_0, IfxGtm_Tom_Ch_15, IfxGtm_ToutSel_a, 7, {&MODULE_P02, 7}, IfxPort_OutputIdx_alt1}

#define WAIT_TIME 10

#define DANGER_SOUND 1
#define OPEN_CLOSE_SOUND 2
#define WELCOME_SOUND 3

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

IfxGtm_Tom_ToutMap g_tom_audio = TOM_AUDIO;
Pwm g_audio;
uint8 g_hz_idx = 0;

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
//soundDo(hz) {
//    Set_Duty_Cycle(&config);
//}

void Init_Audio(void) {
    // 초기값 세팅 필요
    uint16 period = 50000;
    uint16 duty_cycle = 25000;

    // 부저 2개 사용 -> 2개 Setting
    Init_Pwm(&g_audio, &g_tom_audio, period, duty_cycle); // 부저1 PWM pin 9 연결

    return;
}

void Make_Sound(uint32 idx) {
    float32 buzzer[2] = {261.686f, 500.262f};
    uint32 uPeriod = (uint32)(100000000/buzzer[idx]);

    Set_Duty_Period(&g_audio, uPeriod);
    Set_Duty_Ratio(&g_audio, 50);
}

void Play_Door_CloseOpen_Sound(void) {
    /* Initialize a time variable */
    Ifx_TickTime ticksFor10ms = IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, WAIT_TIME);

    Make_Sound(0);
//    waitTime(ticksFor10ms * 100);
//    Make_Sound(1);
//    waitTime(ticksFor10ms * 100);
}

void Play_Danger_Sound(void) {
    // "삐~~~~" 출력은 한가지 음계만 쭉 출력.
    Ifx_TickTime ticksFor10ms = IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, WAIT_TIME);

    Make_Sound(0);
    waitTime(ticksFor10ms * 100);

    return;
}

void Play_Open_Close_Sound(void) {
    // 주기만 변경해주면서 소리 출력.
    float buzzer[2] = {261.686f, 500.262f};

    // TODO: idx 미 선언으로 인한 빌드 에러
//    unsigned int uPeriod = (unsigned int)(100000000/buzzer[idx]);

    // TODO: uPeriod 미 선언으로 인한 빌드 에러
//    Set_Duty_Period(&g_audio, uPeriod);
    Set_Duty_Ratio(&g_audio, 50);
    return;
}
// ------------------------- 부저 2개 각기 다른 period 인가가 되는지 확인하는 코드 ---------------------------------
void Make_sound_two_buzzer(uint32 idx1, uint32 idx2) {
    float buzzer[2] = {261.686f, 100.262f};
    unsigned int uPeriod1 = (unsigned int)(100000000/buzzer[idx1]);
    unsigned int uPeriod2 = (unsigned int)(100000000/buzzer[idx2]);

    Set_Duty_Period(&g_audio, uPeriod1);
    Set_Duty_Period(&g_audio, uPeriod2);

    Set_Duty_Ratio(&g_audio, 50);
    Set_Duty_Ratio(&g_audio, 50);
}

void Play_DoorOpen_Sound_two_buzzer(void){
    /* Initialize a time variable */
    Ifx_TickTime ticksFor10ms = IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, WAIT_TIME);

    Make_sound_two_buzzer(0, 1);
    waitTime(ticksFor10ms * 100);
    Make_sound_two_buzzer(1, 0);
    waitTime(ticksFor10ms * 100);
}

void Play_Audio_Case_Of_Situation(uint8 num){
    switch(num){
        case DANGER_SOUND:
            Play_Door_CloseOpen_Sound();
            break;
        case OPEN_CLOSE_SOUND:
            Play_Danger_Sound();
            break;
        case WELCOME_SOUND:
            // 웰텀 사운드 출력.
            break;
    }
    return;
}
// ------------------------- 부저 2개 각기 다른 period 인가가 되는지 확인하는 코드 ---------------------------------

// ------------------------- LED 2개로 주기는 동일하게하고 듀티비를 다르게해서 테스트한 코드 ----------------------------
//void test_led_init(void){
//    initGtm();
//    initGtmTomPwm(&g_audio); // PWM PIN 6
//    initGtmTomPwm(&g_audio); // PWM PIN 7
//}

// ------------------------- LED 2개로 주기는 동일하게하고 듀티비를 다르게해서 테스트한 코드 ----------------------------
