/**********************************************************************************************************************
 * \file Audio.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Audio.h"

#include "Bsp.h"
#include "IfxGtm_Tom_Pwm.h"
#include "IfxGtm_Tom_Timer.h"
#include "Platform_Types.h"
#include "Delay.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define VOLUME_LEVEL        10                                   /* Volume level in percentage                       */
#define WAIT_TIME           1                                   /* Number of milliseconds to wait during play time  */

#define FREQ_OFF            0
#define FREQ_C              523
#define FREQ_CS             554
#define FREQ_D              587
#define FREQ_DS             622
#define FREQ_E              659
#define FREQ_F              698
#define FREQ_FS             740
#define FREQ_G              784
#define FREQ_GS             830
#define FREQ_A              880
#define FREQ_AS             932
#define FREQ_B              988
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
Ifx_TickTime g_ticksFor1ms;
IfxGtm_Tom_Timer g_buzzer;

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/* Set the volume of the Buzzer */
void setVolume(uint8 volumeLevel);

/* Start the PWM and hence the buzzer */
void playTone(float32 frequency, sint64 length_ms);

void Welcome_Sound(void);
void Warning(void);
//void Emergency(void);
void No_Sound(void);

/*********************************************************************************************************************/
/*--------------------------------------------Function Implementations-----------------------------------------------*/
/*********************************************************************************************************************/
/* This function initializes the PWM for the buzzer */
void Init_Audio(void)
{
    /* Initialize the time variable */
    g_ticksFor1ms = IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, WAIT_TIME);

    IfxGtm_enable(&MODULE_GTM); /* Enable GTM */
    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_FXCLK); /* Enable FX clock */

    IfxGtm_Tom_Timer_Config timerCfg; /* Create an instance of configuration structure */
    IfxGtm_Tom_Timer_initConfig(&timerCfg, &MODULE_GTM); /* Initialize the timer with default values */

    timerCfg.tom = IfxGtm_Tom_1;                                            /* Set TOM to be used                   */
    timerCfg.timerChannel = IfxGtm_Tom_Ch_4;                                /* Set the output channel               */
    timerCfg.clock = IfxGtm_Tom_Ch_ClkSrc_cmuFxclk2;                        /* Set the CMUFX clock                  */
    timerCfg.triggerOut = &IfxGtm_TOM1_4_TOUT30_P33_8_OUT;                  /* Set port and pin for PWM output      */
    timerCfg.base.trigger.enabled = TRUE;                                   /* Enable TOM channel                   */
    timerCfg.base.trigger.outputEnabled = TRUE;                             /* Enable TOM channel output            */
    timerCfg.base.trigger.risingEdgeAtPeriod = TRUE;                        /* Starting PWM with rising edge        */
    IfxGtm_Tom_Timer_init(&g_buzzer, &timerCfg);                            /* Initialize the timer                 */

    /* Enable channel update */
    IfxGtm_Tom_Tgc_enableChannelsUpdate((Ifx_GTM_TOM_TGC *)&g_buzzer.tom->TGC0_GLB_CTRL, 1 << IfxGtm_TOM1_4_TOUT30_P33_8_OUT.channel, 0);

}

void Control_Audio(uint8 state) {
    switch(state) {
    case WELCOME_SOUND:
        Welcome_Sound();
        break;
    case WARNING:
        if (Get_Cur_Millis() % 500 < 250) {
            IfxGtm_Tom_Timer_stop(&g_buzzer);
            IfxGtm_Tom_Timer_run(&g_buzzer);
            IfxGtm_Tom_Timer_setFrequency(&g_buzzer, FREQ_A);
            setVolume(10);
            waitTime(g_ticksFor1ms);
        } else {
            IfxGtm_Tom_Timer_stop(&g_buzzer);
        }
        break;
//    case EMERGENCY:
//        IfxGtm_Tom_Timer_run(&g_buzzer);
//        break;
    case NO_SOUND:
    default:
        No_Sound();
        break;
    }
}

/* This function set the volume of the buzzer */
void setVolume(uint8 volumeLevel)
{
    /* This function allows you to trigger the PWM and adjust the duty cycle to control the volume of the buzzer */
    IfxGtm_Tom_Timer_setTrigger(&g_buzzer, (volumeLevel * (g_buzzer.base.period)) / 150); /* volumeLevel is in percentage */
}

 /* This function plays a tone */
void playTone(float32 frequency, sint64 duration_ms)
{
    if(frequency == 0) /* If frequency is zero then the PWM will not start */
    {
        waitTime(duration_ms * g_ticksFor1ms);                              /* Wait during play time                */
    }
    else
    {
        IfxGtm_Tom_Timer_run(&g_buzzer);                                    /* Start the timer                      */
        IfxGtm_Tom_Timer_setFrequency(&g_buzzer,frequency);                 /* Set frequency to the desired value   */
        setVolume(VOLUME_LEVEL);                                            /* Set volume to VOLUME_LEVEL           */
        waitTime(duration_ms * g_ticksFor1ms);                              /* Wait during play time                */
        setVolume(0);                                                       /* Set volume to 0                      */
        IfxGtm_Tom_Timer_stop(&g_buzzer);                                   /* Stop the timer                       */
    }
}

void Welcome_Sound(void) {
    float32 frequencies[] = {
            FREQ_GS/2, FREQ_A/2, FREQ_E, 0, FREQ_DS, FREQ_FS, FREQ_CS * 2, 0
    };
    float32 durations[] = {
            150, 150, 150, 150, 150, 150, 150, 150
    };
    for(uint16 i = 0; i < sizeof(frequencies) / sizeof(float32); i++)
    {
        playTone(frequencies[i], durations[i]); /* Launch the GTM PWM timer to the frequency the desired value */
    }
}

void Warning(void) {
    if (Get_Cur_Millis() % 1000)
        setVolume(10);
}

//void Emergency(void) {
//
//}

void No_Sound(void) {
    IfxGtm_Tom_Timer_stop(&g_buzzer);
}
