/**********************************************************************************************************************
 * \file Light.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Light.h"

#include "Platform_Types.h"
#include "Pin_Map.h"
#include "Delay.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define     OFF 0   // 0b000
#define     R   4   // 0b100
#define     RG  6   // 0b110
#define     G   2   // 0b010
#define     GB  3   // 0b011
#define     B   1   // 0b001
#define     BR  5   // 0b000
#define     RGB 7   // 0b111

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
uint8 g_led_state = 0;
uint8 g_arr_led[6] = {RG,G,GB,B,BR, RGB};
uint64 g_prev_millis = 0;

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void Init_Light(void) {
    PIN_MODE(PIN_LED_RED, OUTPUT_MODE);
    PIN_MODE(PIN_LED_GREEN, OUTPUT_MODE);
    PIN_MODE(PIN_LED_BLUE, OUTPUT_MODE);

    SET_PIN(PIN_LED_RED, LOW);
    SET_PIN(PIN_LED_GREEN, LOW);
    SET_PIN(PIN_LED_BLUE, LOW);
}

void Control_Light(uint8 state) {
    if (state == TRUE) {
        SET_PIN(PIN_LED_RED, LOW);
        SET_PIN(PIN_LED_GREEN, LOW);
        SET_PIN(PIN_LED_BLUE, LOW);
        g_prev_millis = 0;
        return;
    }
    uint8 red   = g_arr_led[g_led_state] & R;
    uint8 green = g_arr_led[g_led_state] & G;
    uint8 blue  = g_arr_led[g_led_state] & B;

    if (red != 0) {
        SET_PIN(PIN_LED_RED, HIGH);
    } else {
        SET_PIN(PIN_LED_RED, LOW);
    }

    if (green != 0) {
        SET_PIN(PIN_LED_GREEN, HIGH);
    } else {
        SET_PIN(PIN_LED_GREEN, LOW);
    }

    if (blue != 0) {
        SET_PIN(PIN_LED_BLUE, HIGH);
    } else {
        SET_PIN(PIN_LED_BLUE, LOW);
    }

    if (Get_Cur_Millis() - g_prev_millis >= 100) {
        g_led_state = (g_led_state + 1) % 6;
        g_prev_millis = Get_Cur_Millis();
    }
}
